apiVersion: v2
name: ipsec-vpn-server
description: Deploy IPsec VPN server inside K8s with optional sealed-secrets
home: https://helm.task.media/ipsec-vpn-server
keywords:
  - vpn
  - ipsec
  - traefik
sources:
  - https://github.com/hwdsl2/docker-ipsec-vpn-server

type: application

version: 1.1.1

# hwdsl2/docker-ipsec-vpn-server does not provide versioning
# see: https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/98
appVersion: "latest"

icon: https://media.task.media/images/logo.png
