{{- $fullname_vpn_server := (printf "%s-vpn-server" (include "ipsec-vpn-server.fullname" .)) -}}
{{- if .Values.ingress.traefik.enabled }}
{{- range .Values.service.ports }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ $fullname_vpn_server }}-{{ .name }}
spec:
  entryPoints:
    - {{ .name }}
  routes:
    - services:
      - name: {{ $fullname_vpn_server }}
        port: {{ .name }}
---
{{- end }}
{{- end }}
