{{- if .Values.sealed_secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "ipsec-vpn-server.fullname" . }}-vpnconfig
spec:
  encryptedData:
    psk: {{ .Values.vpn.psk }}
{{- range .Values.users }}
    password_{{ .username }}: {{ .password }}
{{- end }}
{{- end }}
