{{- if not .Values.sealed_secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ipsec-vpn-server.fullname" . }}-vpnconfig
data:
  psk: {{ .Values.vpn.psk | b64enc }}
{{- range .Values.users }}
  password_{{ .username }}: {{ .password | b64enc }}
{{- end }}
{{- end }}
