{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ipsec-vpn-server.fullname" . }}-vpn-server
spec:
  selector:
    app.kubernetes.io/name: {{ template "ipsec-vpn-server.fullname" . }}-vpn-server
  ports:
    - name: vpn-isakmp
      port: {{ .Values.service.ports.isakmp }}
      targetPort: vpn-isakmp
      protocol: UDP
    - name: vpn-ike
      port: {{ .Values.service.ports.ike }}
      targetPort: vpn-ike
      protocol: UDP
{{- end }}
