apiVersion: v1
kind: Service
metadata:
  name: {{ template "ipsec-vpn-server.fullname" . }}-vpn-server
spec:
  selector:
    app.kubernetes.io/name: {{ template "ipsec-vpn-server.fullname" . }}-vpn-server
  ports:
    - name: {{ .Values.ingress.ports.isakmp.name }}
      port: {{ .Values.ingress.ports.isakmp.port }}
    - name: {{ .Values.ingress.ports.ike.name }}
      port: {{ .Values.ingress.ports.ike.port }}
